### ISSUE TITLE
Numexpr evaluate function returns zero arrays when running on Xeon processors

### ISSUE THREAD

**Issue by TrekkieByDay** [pydata/numexpr#214] opened 2016-04-07 18:02 UTC
Hello. I've recently discovered what appears to be a bug in Numexpr.

In a nutshell, `evaluate` sometimes (unpredictably) returns incorrect results when doing a straightforward array operation. The bug, which can be reproduced by the code below, results in a zero array being returned rather than the correct result. Although the sample code shows a multiplication, this bug has manifested for us on addition and exponentiation as well. Notably, there are no errors or warnings that are raised by Numexpr, the computational load appears normal (i.e. the RAM and CPU are taxed as expected when monitoring task manager), and the correct shape array is returned. It was a rather insidious bug to isolate for those reasons! In our tests, this bug has only manifested in the following hardware builds:
1. Windows Server 2012 r2, Intel Xeon 2680 v3,
   2 processors, 48 logical cores
2. Windows 8.1, Intel Xeon 2690,
   1 processor, 24 logical cores

In all the many thousands of runs of our software completed on our Windows 7, 64 bit, Intel i7 machines, this has never manifested. Furthermore, we have run the attached code many times (with bigger arrays and more iterations) and have not seen the error on the Windows 7, i7 machines. The Xeon computers, though, manifest it regularly. Unfortunately we don't have any other builds on which to test.

Any advice you have would be greatly appreciated. We have come to depend on Numexpr to do efficient multiprocessing on basic array operations in Python. The possibility of this error manifesting during a long run, though, without any kind of raised error or warning, is very problematic. 

Other items of note:
1. We are running from the WinPython distribution 3.4.3.6 and included Numexpr 2.4.4.
2. We have not invoked any supporting Numexpr functions, just `evaluate`... so we are using its default settings.

Thank you so much for writing such a useful tool, and thank you in advance for any help you can give us.

Sample Code:

```
import numpy as np
import numexpr as ne

x = np.ones(1e6)
y = np.ones(1e6)

for ii in range(1000):

    rr = ne.evaluate('x * y')
    test = np.all(rr == 0)
    if test:
        print('Gotcha! %d' % ii)

print('Complete!')
```

**Comment by robbmcleod** [comment] 2016-04-07 19:47
This isn't really a bug in numexpr.  You're just comparing 64-bit floating point numbers generated on one architecture (MSVC2010 in your case) with one library and finding it has a different tolerance than another library (whatever your numpy was compiled with, probably Atlas).

e.g. 

https://www.google.ch/search?q=equality+with+floating+point

Now if the return value was 42, instead of 1.0E-13, it would be concerning.

**Comment by gdementen** [comment] 2016-04-07 19:50
@robbmcleod here, he gets 0 instead of ones, which IS concerning. No idea where the problem is coming from though.

**Comment by TrekkieByDay** [comment] 2016-04-07 19:50
Hrm. See this: https://github.com/pydata/numexpr/issues/185 and this: https://github.com/pydata/numexpr/issues/188. This apparently was a known issue for 2.4.4... which I'm using in my WinPython distribution. I'm told that this has been fixed in the latest version of Numexpr, so i'll just upgrade.

**Comment by robbmcleod** [comment] 2017-09-09 00:35
Resolved, closing.

**Closed by robbmcleod** 2017-09-09 00:35 UTC
