### ISSUE TITLE
When doing power operation issue encountered  TypeError: '<' not supported between instances of 'str' and 'int' 

### ISSUE THREAD

**Issue by timbrist** [pydata/numexpr#434] opened 2023-04-20 14:34 UTC
TypeError: '<' not supported between instances of 'str' and 'int' 

code:
import numexpr as ne
A = 10
B = 2
print(ne.evaluate("A**B"))

![Screenshot from 2023-04-20 17-30-21](https://user-images.githubusercontent.com/50691556/233399149-8fc57790-bd23-474b-bb11-59b1f77ac4d7.png)

**Comment by timbrist** [comment] 2023-04-21 13:39
> This is a point where I'm unsure what the intention of the original authors was with regards to the attribute `.value` on these `ExpressionNode` objects. Because the 'value' is the variable string, `'a'` and `'b'` here. So there's a lot of the short-circuit code that shouldn't work in this case, because they clearly expect it to be an actual numerical value.
> 
> The documentation for `ASTNode`, which is not connected to `ExpressionNode`, seems to suggest that `value` is a mutable type.
> 
> ```
> class ASTNode(object):
>     """Abstract Syntax Tree node.
> 
>     Members:
> 
>     astType      -- type of node (op, constant, variable, raw, or alias)
>     astKind      -- the type of the result (bool, float, etc.)
>     value        -- value associated with this node.
>                     An opcode, numerical value, a variable name, etc.
>     children     -- the children below this node
>     reg          -- the register assigned to the result for this node.
>     """
> ```
> 
> So, yeah, unsure how this code was intended to work. I might need to go way back in Git to guess.

Hi robmcleod, 
Thank you for the reply, I wasn't planing to dig too much at first, but your reply encourage me to run the source code;

I have debug a little, the attribute .value is supposed to link to .astKind but somehow .value is str, the astkind is forgotten to change; 

well I only add a condition and solve the problem; I will also go further to check the mechanism 

![Screenshot from 2023-04-21 16-37-00](https://user-images.githubusercontent.com/50691556/233650127-7de4d360-5dc1-4ea1-92a8-ef258bd76979.png)

**Comment by timbrist** [comment] 2023-04-21 15:52
things are really bad, I have understood the intention of the power function 
the condition to raise ValueError() is a numpy nagative error

https://stackoverflow.com/questions/43287311/why-cant-i-raise-to-a-negative-power-in-numpy

but as I dig more, things go bad as following example; 
![Screenshot from 2023-04-21 18-45-02](https://user-images.githubusercontent.com/50691556/233679624-7987d442-fff8-4544-931c-10f7dd6f8a69.png)

if the b is a constant node,  then we can raise the error here 

![Screenshot from 2023-04-21 18-49-50](https://user-images.githubusercontent.com/50691556/233680539-6c6d23be-d13f-4982-b5a9-9c3d77a57586.png)

but if y is a the expression, we can not access the variable at this function

**Comment by robbmcleod** [comment] 2023-04-21 16:31
I think in terms of having negative numbers in arrays we probably just have to accept the behaviour of the C++ virtual machine (which outputs zero if the exponent is a negative integer).

The problem is these code shortcuts for singletons. The simplest answer may simply be to remove the shortcuts. They're not very helpful from a performance perspective because the typical use case is when people are using NumExpr as a parser. IIRC, it takes about 1 ms to spin up the virtual machine in 2.X.

**Comment by timbrist** [comment] 2023-04-21 16:46
I don't whether github owner will see this issue. 
since I didn't have the push permission, I will stop here

![Screenshot from 2023-04-21 19-39-55](https://user-images.githubusercontent.com/50691556/233690267-82ba7f2e-d145-4338-a044-cc6a2034dd1c.png)

I believe that numpy Error should not be handle in pow_op(a,b) ; 
And we have to accept the fact that x**-2, if x is a integer(number or vector)  then answer is 0;

**Comment by timbrist** [comment] 2023-04-21 16:49
> I think in terms of having negative numbers in arrays we probably just have to accept the behaviour of the C++ virtual machine (which outputs zero if the exponent is a negative integer).
> 
> The problem is these code shortcuts for singletons. The simplest answer may simply be to remove the shortcuts. They're not very helpful from a performance perspective because the typical use case is when people are using NumExpr as a parser. IIRC, it takes about 1 ms to spin up the virtual machine in 2.X.

Thanks for the reply,  I spent hours on this and you are right we just need to accept the behavior of the C++ virtual machine.

**Comment by robbmcleod** [comment] 2023-08-06 21:14
Closing with release of 2.8.5.

**Closed by robbmcleod** 2023-08-06 21:14 UTC
