### ISSUE TITLE
calculation error : NUMEXPR 2.4.4, Python 3.4.3, Pandas 0.17 or 0.16.x, Windows 7/10 64bit

### ISSUE THREAD

**Issue by apiszcz** [pydata/numexpr#188] opened 2015-10-29 08:55 UTC
When numexpr is available to pandas the first two rows of a pandas dataframe have incorrect values. When I remove numexpr availability to Pandas the values are computed correctly.

Operation 1 (copy) data, values are correct
Operation 2 (add) values in first two rows are set to a small values (e.g.) 2.4-312.

df['new']=df['a'].copy()
df['new']=+10.0 

Using numpy directly produces correct result.
Using pandas without numexpr produces correct result.
Using pandas with numexpr produces erroneous results.

I see the same type of result for multiplication. It only affects the first two rows in dataframe.

===VERIFIED 2.4.3 works!!!!!!!!!!!!!!!!!!!!!

100 test runs

The issue with high probability is with numexpr 2.4.4

**Comment by FrancescAlted** [comment] 2015-10-29 08:59
Could you please send a minimal, self-contained example using just numexpr and NumPy showing the problem?  Thanks!

**Comment by apiszcz** [comment] 2015-10-29 09:02
The answer is maybe, the system I see this behavior on is producing different results than the system I can create examples for github. I tried to reproduce for pandas crew and have not succeeded. I am certain there is an interaction, btw the incorrect result occurs 'randomly' about 3 out of 100 runs, using identical input data.

**Comment by FrancescAlted** [comment] 2015-10-29 09:13
Hmm, I recently reverted a commit that may have something to do with what you are experiencing: https://github.com/pydata/numexpr/commit/70bf71bc5aaba59da83b7c87fb2915d0680459ad. Could you have it a try?

**Comment by apiszcz** [comment] 2015-10-29 09:17
I can test anything, however it will take a while. If 2.4.1 or earlier works, which I have on the system, we'll know more.

**Comment by apiszcz** [comment] 2015-10-29 16:36
I am unable to reproduce the with 2.4.3. The problem arises with 2.4.4 on a
Windows server 2012 system with 64 logical CPUS and a reasonably heavy
workload. Testing on a WS2012 server 24 logical cpu XEON that is similar
does not exhibit the problem for 2.4.4. Testing on a Windows 7 quad core
hyperthreading CPU does not indicate any issues.

**Comment by FrancescAlted** [comment] 2015-10-29 18:57
Ah, great, then the cause is probably fixed in master already.  Just to make sure, can you have master a try?  If it goes well I'll do a release soon.

**Comment by apiszcz** [comment] 2015-10-29 19:07
unfortunately I need a compiled module for Windows , python 64 to test
anything newer than what is at http://www.lfd.uci.edu/~gohlke/pythonlibs/,
however reading your change, (race condition) it sounds like the cause and
esp since there were so few windows specific changes. I'm curious though,
is this an ongoing issue that someone may have encountered before.

**Comment by apiszcz** [comment] 2015-10-29 19:08
I can test and update once the new release is available.

**Comment by FrancescAlted** [comment] 2015-10-29 19:09
Ok, no problem.  And yes, a similar issue was already reported: https://github.com/pydata/numexpr/issues/185.

**Closed by FrancescAlted** 2015-10-29 19:09 UTC

**Comment by apiszcz** [comment] 2015-10-29 19:41
PERFECT and agree, and kind of 'nasty'!
Thank you.
