### ISSUE TITLE
Wrong evaluation results

### ISSUE THREAD

**Issue by roman-kh** [pydata/numexpr#144] opened 2014-05-02 20:51 UTC
I bumped into a strange behavior of numexpr - a simple division operation gives a wrong result. Here is the code:
```
from __future__ import division
import numexpr as ne
import pandas as pd
import numpy as np

nn=10000
a=np.array([np.random.randint(1,1000) for i in xrange(nn)])
b=np.array([np.random.randint(1,1000) for i in xrange(nn)])
df=pd.DataFrame({'a':a,'b':b})

a2=df.a[1:]
b2=df.b[:-1]
c2=df.eval('a2/b2')
c3=ne.evaluate("a2/b2")
```

So the results of pandas.eval and numexpr.evaluate differ, with numexpr returning the wrong answer.
Interestingly, the code below gives same result for both evaluations:
```
a2=df.a
b2=df.b
c2=df.eval('a2/b2')
c3=ne.evaluate("a2/b2")
```

**Comment by jennolsen84** [comment] 2016-01-28 08:39
I had to change a few things.  I think `df.eval` is now `pd.eval`.

But, I think the reason for the difference is due to what pandas is doing.  When you divide two dataframes, pandas is matching up all the labels.  I am guessing numexpr just extracts the values from the dataframes and does a simple division.  Pandas is higher level than numexpr, so it doesn't make sense for numexpr to know lining up labels, etc.

So, the difference is likely due to the API.  Someone more familiar with numexpr can probably comment more and close the issue as 'not a bug'.

**Comment by FrancescAlted** [comment] 2016-01-28 09:07
I agree with @jennolsen84.  In order to check that numexpr is working well or not, you need to feed it with numpy arrays and compare against numpy results.  Pandas objects can behave differently.

**Closed by FrancescAlted** 2016-01-28 09:07 UTC
Labels: invalid
