### ISSUE TITLE
Numexpr is using large amounts of memory on import

### ISSUE THREAD

**Issue by simonrp84** [pydata/numexpr#341] opened 2019-08-05 14:29 UTC
Hello,
I've discovered that numexpr is using approx. 1Gb of memory per thread simply when the library is imported.

Here is some sample code that demonstrates the issue:
```
import subprocess
import os
my_pid = os.getpid()

try:
    import numexpr as ne
except ImportError:
    ne = None

p = subprocess.Popen("grep VmPeak /proc/"+str(my_pid)+"/status", stdout=subprocess.PIPE, shell=True)
(output, err) = p.communicate()
p_status = p.wait()
print(os.environ['NUMEXPR_MAX_THREADS'],output[8:20].decode())
```
And an example of the output, where `test2.py` is the code given above:
```
for i in {4..56..4}; do export NUMEXPR_MAX_THREADS=$i; python test2.py ; done
4  4080524 kB
8  8080540 kB
12 12080556 kB
16 16080572 kB
20 20080588 kB
24 24080604 kB
28 28080620 kB
32 32080636 kB
36 36080652 kB
40 40080668 kB
44 44080684 kB
48 48080700 kB
52 52080716 kB
56 56080732 kB
```

This occurs both in the `2.6.9` release and in the latest github build, `2.6.10dev0`.

Is this expected? It seems like a lot of memory to be used just when importing.
In case helpful for debugging: I've tried this code on linux machines with between 8 - 128 cores. The operating systems tested are: Ubuntu 14.04, 16.04, 18.04, Mint 19.

(edit) This is on a fresh python / conda install py the way. Here's the output of `conda list`:
```
# Name                    Version                   Build  Channel
bzip2                     1.0.8                h516909a_0    conda-forge
ca-certificates           2019.6.16            hecc5488_0    conda-forge
certifi                   2019.6.16                py37_1    conda-forge
libblas                   3.8.0               11_openblas    conda-forge
libcblas                  3.8.0               11_openblas    conda-forge
libffi                    3.2.1             he1b5a44_1006    conda-forge
libgcc-ng                 9.1.0                hdf63c60_0    anaconda
libgfortran-ng            7.3.0                hdf63c60_0    anaconda
liblapack                 3.8.0               11_openblas    conda-forge
libopenblas               0.3.6                h6e990d7_6    conda-forge
libstdcxx-ng              9.1.0                hdf63c60_0    anaconda
ncurses                   6.1               hf484d3e_1002    conda-forge
numexpr                   2.6.10.dev0              pypi_0    pypi
numpy                     1.17.0           py37h95a1406_0    conda-forge
openssl                   1.1.1c               h516909a_0    conda-forge
pip                       19.2.1                   py37_0    conda-forge
python                    3.7.3                h33d41f4_1    conda-forge
readline                  8.0                  hf8c457e_0    conda-forge
setuptools                41.0.1                   py37_0    conda-forge
sqlite                    3.29.0               hcee41ef_0    conda-forge
tk                        8.6.9             hed695b0_1002    conda-forge
wheel                     0.33.4                   py37_0    conda-forge
xz                        5.2.4             h14c3975_1001    conda-forge
zlib                      1.2.11            h516909a_1005    conda-forge
```

**Comment by robbmcleod** [comment] 2019-08-05 15:24
Ok, strange, I would suspect it's something to do with the MKL library if you are using NumExpr built by Anaconda. I'm at a conference this week so I may not be able to get to a Linux box until next week.

**Comment by FrancescAlted** [comment] 2019-08-05 17:06
I cannot reproduce this in my Ubuntu 18.04 box:

```
$ for i in {4..56..4}; do export NUMEXPR_MAX_THREADS=$i; python3 test2.py ; done
4   324084 kB
8   324084 kB
12   324084 kB
16   324084 kB
20   324084 kB
24   324084 kB
28   324084 kB
32   324084 kB
36   324084 kB
40   324084 kB
44   324084 kB
48   324084 kB
52   324084 kB
56   324084 kB
```

I am using conda with numexpr compiled with VML/MKL support:

```
$ python -c"import numexpr; numexpr.print_versions()"
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
Numexpr version:   2.6.4
NumPy version:     1.16.4
Python version:    3.6.8 |Anaconda, Inc.| (default, Dec 30 2018, 01:22:34)
[GCC 7.3.0]
Platform:          linux-x86_64
AMD/Intel CPU?     True
VML available?     True
VML/MKL version:   Intel(R) Math Kernel Library Version 2019.0.4 Product Build 20190411 for Intel(R) 64 architecture applications
Number of threads used by default: 8 (out of 8 detected cores)
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
```

**Comment by pnuu** [comment] 2019-08-05 18:27
I tested with Python 2.7 (`pip install numpy; pip install numexpr` to a fresh virtualenv), and Python 3.7.3 (fresh conda env, `numexpr` installed separately with `pip` and `conda install`). I got similar results as @FrancescAlted, memory usage from 211 MB to 253 MB, depending on the Python version and installation method. First three threads stay at one level, for the fourth there's a increase of ~10 MB, further threads get no increase (only got four cores, Intel N4100).

Even if I don't have it nearly as bad as @simonrp84, I still think 200+ MB for plain import is quite much...

**Comment by FrancescAlted** [comment] 2019-08-05 19:03
Well, in my box is more 325 MB irregardingly of the number of threads.  At any rate, I am pretty sure that MKL is a pretty nice memory hugger.  If you prefer numexpr to use less memory, you can always compile it without MKL support (just remove `site.cfg`).  In my case, numexpr without MKL gives:

```
$ for i in {4..56..4}; do export NUMEXPR_MAX_THREADS=$i; python test2.py ; done
4    27408 kB
8    27408 kB
12    27408 kB
16    27408 kB
20    27408 kB
24    27408 kB
28    27408 kB
32    27408 kB
36    27408 kB
40    27408 kB
44    27408 kB
48    27408 kB
52    27408 kB
56    27408 kB
```

and 27 MB is as low as it gets.

**Comment by simonrp84** [comment] 2019-08-06 08:00
Thanks for the replies. I do not have MKL installed (as you can see from the Conda list output), so that cannot be the source of the issue..

**Comment by bashtage** [comment] 2019-08-06 08:26
What happens if you use a fresh virtual env that only uses packages from PyPI?

**Comment by pnuu** [comment] 2019-08-06 08:36
@bashtage my Python 2.7 and the first `conda` installation used only packages from PyPI, no `mkl` in any of the three.

**Comment by bashtage** [comment] 2019-08-06 08:40
It looks like many are from conda-forge and some from anaconda.  What I had in mind was 

```
conda create -n test python=2.7
conda activate test
pip install pip --upgrade
pip install numexpr
```

**Comment by bashtage** [comment] 2019-08-06 08:41
Your conda (and the fact numpy is 1.17) indicates are you using 3.7.

**Comment by pnuu** [comment] 2019-08-06 08:51
Yes, `conda` installation is Python 3.7 (and was otherwise exactly what you suggested). The Python 2.7 test was done to a fresh virtualenv with nothing else than packages installed with `pip`. With Python 2.7 from `conda` and numexpr from `pip` I get similar results:
```python
$ for i in `seq 1 8`; do NUMEXPR_MAX_THREADS=$i python test.py; done
('1', u'  222700 kB\n')
('2', u'  222700 kB\n')
('3', u'  222700 kB\n')
('4', u'  230896 kB\n')
('5', u'  230896 kB\n')
('6', u'  230896 kB\n')
('7', u'  230896 kB\n')
('8', u'  230896 kB\n')
```
```
$ python -c "import numexpr; numexpr.print_versions()"
*Warning*: NumPy version is lower than recommended: 1.16.4 < 1.7.0
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
Numexpr version:   2.6.9
NumPy version:     1.16.4
Python version:    2.7.15 | packaged by conda-forge | (default, Jul  2 2019, 00:39:44) 
[GCC 7.3.0]
Platform:          linux2-x86_64-#26~18.04.1-Ubuntu SMP Thu Jun 27 07:28:31 UTC 2019
CPU vendor:        
CPU model:         
CPU clock speed:    MHz
VML available?     False
Number of threads used by default: 4 (out of 4 detected cores)
Maximum number of threads: 64
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
```

**Comment by simonrp84** [comment] 2019-08-06 09:05
@bashtage I just tried this using the commands you suggest. numexpr is still using ~1Gb per thread on import.

**Comment by bashtage** [comment] 2019-08-06 09:09
Have you tried setting everything to be single-threaded (except numexpr)?

```
export OPENBLAS_NUM_THREADS=1
export OMP_NUM_THREADS=1
export MKL_NUM_THREADS=1
```

**Comment by pnuu** [comment] 2019-08-06 12:03
Conda, Python 2.7.15, `numexpr` and `numpy` installed with `pip`:
```
$ for mod in OPENBLAS_NUM_THREADS OMP_NUM_THREADS MKL_NUM_THREADS; do export ${mod}=1; NUMEXPR_MAX_THREADS=4 python test.py; unset $mod; done
('4', u'   99820 kB\n')
('4', u'   99824 kB\n')
('4', u'  230896 kB\n')
```

System Python 2.7.15, new virtualenv, `numexpr` and `numpy` installed with `pip`:
```
('4', u'  154720 kB\n')
('4', u'  121936 kB\n')
('4', u'  253040 kB\n')
```

Conda, Python 3.7.3, `numexpr` and `numpy` installed with `pip`:
```
$ for mod in OPENBLAS_NUM_THREADS OMP_NUM_THREADS MKL_NUM_THREADS; do export ${mod}=1; NUMEXPR_MAX_THREADS=4 python test.py; unset $mod; done
4   157956 kB
4   125172 kB
4   256260 kB
```

**Comment by simonrp84** [comment] 2019-08-06 12:07
Same test for me, on the clean env installed with the steps below.
Results:
```
('4', u' 4091504 kB\n')
('4', u'   91488 kB\n')
('4', u' 7319868 kB\n')
```

OMP_NUM_THREADS seems to be the biggest culprit.
 
> ```
> conda create -n test python=2.7
> conda activate test
> pip install pip --upgrade
> pip install numexpr
> ```

**Comment by pnuu** [comment] 2019-08-06 12:16
And setting all of the env variables gives the same memory usage as `export OMP_NUM_THREADS=1` alone.

**Comment by gdementen** [comment] 2019-08-06 12:38
Just out of curiosity, I wonder how much numexpr actually contributes to the memory usage compared to the same test which would only import numpy.

**Comment by pnuu** [comment] 2019-08-06 13:58
It indeed seems like it's Numpy import that consumes most of the memory. The addition from `numexpr` is in the order of 4 to 40 MB, depending which env variable is set and which installation is used. If @simonrp84 can confirm that same happens on his system where the problem is at out-of-control level and escalates even with the plain Numpy import with increasing `NUMEXPR_MAX_THREADS`, we can close this an move over to Numpy :-)

**Comment by simonrp84** [comment] 2019-08-06 14:12
Here's some more comprehensive tests.

Importing *only* numpy:
Constant: `OPENBLAS_NUM_THREADS=1`
Variable: `OMP_NUM_THREADS=4...56`
Result: *Fixed* memory usage on import, 87700kB

Importing *only* numpy:
Variable: `OPENBLAS_NUM_THREADS=4..56`
Constant: `OMP_NUM_THREADS=1`
Result: *Variable* memory usage on import, 3186032kB for 4 BLAS threads, 56890180kB for 56 BLAS threads.


Importing *only* numexpr:
Constant: `OPENBLAS_NUM_THREADS=1`
Variable: `OMP_NUM_THREADS=4...56`
Result: *Variable* memory usage on import, 4092092kB for one OMP thread, 56092300kB for 56 OMP threads.

Importing *only* numexpr:
Variable: `OPENBLAS_NUM_THREADS=4...56`
Constant: `OMP_NUM_THREADS=1`
Result: *Variable* memory usage on import, 3190392kB for one BLAS thread, 56894552kB for 56 BLAS threads.

In all cases `NUMEXPR_MAX_THREADS=1`

Hope that helps.

**Comment by bashtage** [comment] 2019-08-06 14:30
You probably should try a different OpenBlas kernel.

See

```
The environment variable which control the kernel selection is OPENBLAS_CORETYPE (see driver/others/dynamic.c) e.g. export OPENBLAS_CORETYPE=Haswell. And the function char* openblas_get_corename() returns the used target.
```

https://github.com/xianyi/OpenBLAS/blob/develop/driver/others/dynamic.c

**Comment by bashtage** [comment] 2019-08-06 14:50
In particular, you should try Sandybridge is you aren't already using it.

**Comment by robbmcleod** [comment] 2019-09-09 17:47
I think we can close this as it appears to be a downstream issue with some installs of NumPy?

**Comment by robbmcleod** [comment] 2020-09-21 23:41
Closing as appears to be stale.

**Closed by robbmcleod** 2020-09-21 23:41 UTC
