### ISSUE TITLE
Support for Python 3 Strings

### ISSUE THREAD

**Issue by PeterKucirek** [pydata/numexpr#281] opened 2017-09-12 15:31 UTC
It appears that NumExpr does not accept Python 3 string arrays, regardless of how they are sanitized before evaluation.

Consider the following code:

```python
import numpy as np
import numexpr as ne
x = np.array(list('abcdefg'), dtype='S1')
ne.evaluate("where(x == 'd', 10, 5)")
```

On Python2.7, this evaluates to `array([ 5,  5,  5, 10,  5,  5,  5])`, but on Python3.6 a `TypeError` is raised:
```
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
C:\ProgramData\Miniconda3\lib\site-packages\numexpr\necompiler.py in evaluate(ex, local_dict, global_dict, out, order, casting, **kwargs)
    793     try:
--> 794         compiled_ex = _numexpr_cache[numexpr_key]
    795     except KeyError:

KeyError: ("where(x == 'd', 10, 5)", (('optimization', 'aggressive'), ('truediv', False)), (('x', <class 'bytes'>),))

During handling of the above exception, another exception occurred:

TypeError                                 Traceback (most recent call last)
<ipython-input-7-049656bd2344> in <module>()
----> 1 ne.evaluate("where(x == 'd', 10, 5)")

C:\ProgramData\Miniconda3\lib\site-packages\numexpr\necompiler.py in evaluate(ex, local_dict, global_dict, out, order, casting, **kwargs)
    795     except KeyError:
    796         compiled_ex = _numexpr_cache[numexpr_key] = \
--> 797                       NumExpr(ex, signature, **context)
    798     kwargs = {'out': out, 'order': order, 'casting': casting,
    799               'ex_uses_vml': ex_uses_vml}

C:\ProgramData\Miniconda3\lib\site-packages\numexpr\necompiler.py in NumExpr(ex, signature, **kwargs)
    607     context = getContext(kwargs, frame_depth=1)
    608     threeAddrProgram, inputsig, tempsig, constants, input_names = \
--> 609         precompile(ex, signature, context)
    610     program = compileThreeAddrForm(threeAddrProgram)
    611     return interpreter.NumExpr(inputsig.encode('ascii'),

C:\ProgramData\Miniconda3\lib\site-packages\numexpr\necompiler.py in precompile(ex, signature, context)
    564 
    565     input_order = getInputOrder(ast, input_order)
--> 566     constants_order, constants = getConstants(ast)
    567 
    568     if isReduction(ast):

C:\ProgramData\Miniconda3\lib\site-packages\numexpr\necompiler.py in getConstants(ast)
    334     constants_order = [const_map[v] for v in ordered_constants]
    335     constants = [convertConstantToKind(a.value, a.astKind)
--> 336                  for a in constants_order]
    337     return constants_order, constants
    338 

C:\ProgramData\Miniconda3\lib\site-packages\numexpr\necompiler.py in <listcomp>(.0)
    334     constants_order = [const_map[v] for v in ordered_constants]
    335     constants = [convertConstantToKind(a.value, a.astKind)
--> 336                  for a in constants_order]
    337     return constants_order, constants
    338 

C:\ProgramData\Miniconda3\lib\site-packages\numexpr\necompiler.py in convertConstantToKind(x, kind)
    323     if kind == 'float':
    324         return numpy.float32(x)
--> 325     return kind_to_type[kind](x)
    326 
    327 

TypeError: string argument without an encoding
```

Is there any support for strings in Python 3? Or am I missing some kind of conversion beforehand?

NumPy versions:
 - Python3:  v1.12.1.
 - Python2: v1.9.2rc1

NumExpr versions:
 - Python3: v2.6.2
 - Python2: v2.4

**Comment by robbmcleod** [comment] 2017-09-12 16:55
Hi,

The problem is your 'd' literal is a `str` and not a `bytes`:
   
    import numpy as np
    import numexpr as ne
    x = np.array(list('abcdefg'), dtype='S1')
    ne.evaluate("where(x == b'd', 10, 5)")

works as expected. I'll look into inserting an automatic encode with 'ascii'.

**Comment by PeterKucirek** [comment] 2017-09-12 16:58
Ahhh, now I understand. Thanks for the tip!

**Comment by robbmcleod** [comment] 2017-09-12 17:06
Fix is pushed, a new maintenance update for NumExpr 2.6 should be done sometime soon as it seems past due. Until then you can either clone the repo and build it yourself or use the workaround.  Thanks for the well-formatted bug report.

Closing.

**Closed by robbmcleod** 2017-09-12 17:06 UTC
