### ISSUE TITLE
print_versions() wrongly claims that my numpy version is too low

### ISSUE THREAD

**Issue by Ethunxxx** [pydata/numexpr#327] opened 2018-11-22 09:53 UTC
When I type 

```
import numexpr as ne
ne.print_versions()
```

I get the following warning, which is clearly a mistake:

`*Warning*: NumPy version is lower than recommended: 1.15.4 < 1.7.0`

**Comment by robbmcleod** [comment] 2018-11-30 02:53
Seems to work with the current development version.

Probably dupe of: 

https://github.com/pydata/numexpr/issues/314

What version of `numexpr` is this with?

**Comment by Ethunxxx** [comment] 2018-12-04 08:30
This is the full output I get:

```
*Warning*: NumPy version is lower than recommended: 1.15.4 < 1.7.0
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
Numexpr version:   2.6.8
NumPy version:     1.15.4
Python version:    3.6.6 |Anaconda custom (64-bit)| (default, Oct  9 2018, 12:34:16) 
[GCC 7.3.0]
Platform:          linux-x86_64-#42-Ubuntu SMP Tue Oct 23 15:48:01 UTC 2018
CPU vendor:        
CPU model:         
CPU clock speed:    MHz
VML available?     True
VML/MKL version:   Intel(R) Math Kernel Library Version 2018.0.3 Product Build 20180406 for Intel(R) 64 architecture applications
Number of threads used by default: 8 (out of 8 detected cores)
Maximum number of threads: 64
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
```

**Comment by robbmcleod** [comment] 2018-12-21 18:49
Try upgrading to the newly release 2.6.9 and see if it's fixed?

**Comment by nieder** [comment] 2019-01-01 12:55
I still see it with 2.6.9. 
`*Warning*: NumPy version is lower than recommended: 1.14.5 < 1.7.0`
The changelog from 2.6.8 to HEAD doesn't show any actual code change on version checks.
https://github.com/pydata/numexpr/compare/v2.6.8...master

**Comment by dhomeier** [comment] 2019-01-16 19:50
Looks like a simple typo in the version test:
https://github.com/pydata/numexpr/blob/6a9f2ad1128a4f6577d2cb9967dab0f89698131c/numexpr/tests/test_numexpr.py#L1045

should be
```
if minimum_numpy_version > np_version:
```
:)

**Comment by robbmcleod** [comment] 2019-01-28 21:20
Appears to be fixed. Sorry for taking so long for a trivial fix.

**Closed by robbmcleod** 2019-01-28 21:20 UTC
