### ISSUE TITLE
unorderable types exception when using complex literals

### ISSUE THREAD

**Issue by anntzer** [pydata/numexpr#209] opened 2016-03-28 05:16 UTC
Python 3.5.1, numexpr 2.5

```
In [40]: a = np.array([1]); ne.evaluate("a * 1j + 2")
---------------------------------------------------------------------------                     
KeyError                                  Traceback (most recent call last)                     
/usr/lib/python3.5/site-packages/numexpr/necompiler.py in evaluate(ex, local_dict, global_dict, out, order, casting, **kwargs)                                                                  
    764         try:                                                                            
--> 765             compiled_ex = _numexpr_cache[numexpr_key]                                   
    766         except KeyError:                                                                

KeyError: ('a * 1j + 2', (('optimization', 'aggressive'), ('truediv', False)), (('a', <class 'numpy.int64'>),))                                                                                 

During handling of the above exception, another exception occurred:                             

TypeError                                 Traceback (most recent call last)                     
<ipython-input-40-fd33d7f423e7> in <module>()                                                   
----> 1 a = np.array([1]); ne.evaluate("a * 1j + 2")                                            

/usr/lib/python3.5/site-packages/numexpr/necompiler.py in evaluate(ex, local_dict, global_dict, out, order, casting, **kwargs)                                                                  
    766         except KeyError:                                                                
    767             compiled_ex = _numexpr_cache[numexpr_key] = \                               
--> 768                 NumExpr(ex, signature, **context)                                       
    769         kwargs = {'out': out, 'order': order, 'casting': casting,                       
    770                   'ex_uses_vml': ex_uses_vml}                                           

/usr/lib/python3.5/site-packages/numexpr/necompiler.py in NumExpr(ex, signature, **kwargs)      
    577     context = getContext(kwargs, frame_depth=1)                                         
    578     threeAddrProgram, inputsig, tempsig, constants, input_names = \
--> 579         precompile(ex, signature, context)
    580     program = compileThreeAddrForm(threeAddrProgram)
    581     return interpreter.NumExpr(inputsig.encode('ascii'),

/usr/lib/python3.5/site-packages/numexpr/necompiler.py in precompile(ex, signature, context)
    534 
    535     input_order = getInputOrder(ast, input_order)
--> 536     constants_order, constants = getConstants(ast)
    537 
    538     if isReduction(ast):

/usr/lib/python3.5/site-packages/numexpr/necompiler.py in getConstants(ast)
    301         const_map[(a.astKind, a.value)] = a
    302     ordered_constants = list(const_map.keys())
--> 303     ordered_constants.sort()
    304     constants_order = [const_map[v] for v in ordered_constants]
    305     constants = [convertConstantToKind(a.value, a.astKind)

TypeError: unorderable types: int() < complex()
```

**Comment by gdementen** [comment] 2016-03-31 08:06
seems like a duplicate of #81

**Comment by jonathanessen** [comment] 2017-06-25 18:26
I suspect that the hack by @FrancescAlted in [#81](https://github.com/pydata/numexpr/issues/81) would have a big impact on performance for large input arrays. In most cases, commenting out ordered_constants.sort() in necompiler.py (line 303 in @anntzer's post) would have a negligible impact on the result of the computation.

It seems to me that the reason for the sorting is to minimize roundoff errors, which are most significant when the inputs have very different floating-point exponents, cf. Numerical Recipes Ch 1.

I believe the most correct solution to this issue is to make sure that complex inputs are manipulated in such a way as to minimize the roundoff errors. This seems like an elementary problem which should have a clean solution.

**Comment by robbmcleod** [comment] 2017-06-26 19:59
Umm... why don't we just change it to use `numpy.argsort()` instead?  This problem is because NumExpr 2.6 tries to use Python's built-in types.  
   
    import numpy
    ordered_constants = [complex(2j+1), int(2), float(1E-7)]
    ordered_constants = [ordered_constants[index] for index in numpy.argsort(ordered_constants)]
    print( ordered_constants )

This sorts without errors and without changing the underlying types of the list being sorted.

**Comment by robbmcleod** [comment] 2017-06-27 01:00
Ok after looking into this I have no idea what the sort is for.  The values being sorted are actually tuples,

    ordered_constants = [ ('complex',2j), ('complex', 3) ]

Python sorts tuples on first element, then second, so this would cluster 'complex' alphabetically and then and then the value, which is a weird way to do things.  However while the second item in the list is of ast.kind 'complex' (which is just a string) the type of the second item is int and not complex.  And the function `def sortNodesByOrder()` isn't invoked anywhere. So this looks a bit like a partially implemented feature.

The sensible thing to do would be to implement `__lt__()` in the AST class.

**Comment by robbmcleod** [comment] 2017-06-27 01:11
@jonathanessen would you please clone and test the master now with commit  1812d9b ?  I ran it through the test suite and Francesc's code in #88 plus a few more example, but if it's something you're using it would be nice to get some more feedback.

**Comment by FrancescAlted** [comment] 2017-06-27 16:25
@robbmcleod I suppose you meant #81, not #88.  Regarding the issue, the suggested hack was not by me, so please feel free to implement whatever makes more sense.

**Comment by jonathanessen** [comment] 2017-06-27 16:43
@robbmcleod I tried your commit and it works in my test case: sympy.lambdify no longer fails with the numexpr backend on complex data.

Thank you for looking into this!

**Comment by robbmcleod** [comment] 2017-06-28 04:29
Francesc, yeah I've seen there are a bunch of imported issue from the Google code repo. I think this one is dealt with now. I'll leave the commit message as I don't want to mess with that but I made the correction in the release notes to #81.  Closing.

**Closed by robbmcleod** 2017-06-28 04:29 UTC

**Comment by FrancescAlted** [comment] 2017-06-28 07:12
Excellent.  Thanks!
