### ISSUE TITLE
complex varaible power gives an error

### ISSUE THREAD

**Issue by minjaep** [pydata/numexpr#401] opened 2022-02-21 14:51 UTC
Here is a minimal example:

```
import numpy as np
import numexpr as ne

a=0.5
print(ne.evaluate("(-1)**0.5"))
print(ne.evaluate("(-1)**a"))
```

The first gives a correct number 1j while the second gives nan. I found this is reproducible with any complex variable power.

**Comment by robbmcleod** [comment] 2022-02-24 18:36
This is working as intended as it mimics NumPy behavior. NumExpr does not coerce types for you. If you want to get the actual answer back, the mantissa must have a `dtype` of `complex64` or `complex128`.

    import numpy as np
    import numexpr as ne

    b = -np.ones([2, 2], dtype=np.float32)
    a = -np.ones([2, 2], dtype=np.complex64)
    n = 0.5

    result_ne_a = ne.evaluate('a**n')
    result_ne_b = ne.evaluate('b**n')

    print(result_ne_a)
    print(result_ne_b)

    result_np_a = a**n
    result_np_b = b**n

    print(result_np_a)
    print(result_np_b)

The reason the first one works is because it's a fully constant equation and NumExpr short-circuits the virtual machine and evaluates it with Python rather than the virtual machine. I.e. the output of `(-1)**0.5` is the Python type `complex`, not a NumPy type.

Please see casting rules for areas where NumExpr deviates from NumPy: https://numexpr.readthedocs.io/projects/NumExpr3/en/latest/user_guide.html#casting-rules

Closing.

**Closed by robbmcleod** 2022-02-24 18:36 UTC
